#!/usr/bin/env python
.DEFAULT_GOAL := all
.PHONY: all sender receiver clean

all: sender receiver

sender: 
	echo "chmod +x sender.py"

receiver: 
	echo "chmod +x receiver.py"

clean:
	rm -f port